blank_issues_enabled: false
contact_links:
  - name: Documentation du projet
    url: https://github.com/gabrielluthun/tgvmax-platform/blob/main/README.md
    about: Consultez la documentation avant de créer une issue.
